### PR TITLE
Version 3.1.4

### PR DESCRIPTION
**Pull request by sschuessler**

### CODE REVIEW

**Comment by RESO-RETS** [comment]
Stuart,

Can you make sure the readme and license files are there as well on the new
upload?

Thanks!




Jeremy Crawford
*CEO*
*Real Estate Standards Organization*
[image: Real Estate Standards Organization]
110 Horizon Drive, Ste. 210
Raleigh, NC  27615
C *858-775-2368 <%28858%29%20775-2368>* | O *919-459-6097
<%28919%29%20459-6097>* | E  jeremy@reso.org <%C2%A0jeremy@reso.org> | W
reso.org

*Please be advised I will be out of the office with limited access to
voicemail and email starting July 29th, returning August 6th and responses
may be delayed.

 Follow us on:
[image: id:image001.png@01D290CC.CE030C00]
<https://www.linkedin.com/company-beta/3822604/>    [image:
id:image002.png@01D290CC.CE030C00]
<https://www.facebook.com/Real-Estate-Standards-Organization-RESO-255006121260/>
    [image: id:image003.png@01D290CC.CE030C00]
<https://twitter.com/RESO_RETS?lang=en>    [image:
id:image004.png@01D290CC.CE030C00]
<https://www.instagram.com/reso_rets/?hl=en>   [image:
id:image005.png@01D290CC.CE030C00]
<https://www.youtube.com/channel/UCxi0atov7GtgR67tqO35vAg>
<https://www.pinterest.com/realestatestandardsorg/pins/>

**Comment by etewiah** [comment]
Wow, if this last comment is really by Jeremy Crawford I'll be stunned.  I've been researching open source in the real estate sector and had come to the conclusion that there really wasn't a will to truly engage with the open source community on the part of RESO, NAR etc.
If the CEO of RESO is really taking the time to participate in this open source project then perhaps I'm mistaken.....

**Comment by RESO-RETS** [comment]
Ed,

Not only are we engaged in open source, we paid to have this Reference Client developed and made it available to the community in an open source manner, and I am taking the time to participate in this open source project as well as many others.  You can see a list of open source tools either created by RESO or hosted by RESO at https://reso.org as well as within our GitHub repository.  RESO is an open source standards organization, that is the basis of our existence.  Feel free to reach out to me directly at jeremy@reso.org if you would like further details or have additional questions.  
Sincerely, Jeremy

**Comment by etewiah** [comment]
Thank you Jeremy for taking the time to reply. Really appreciate it. 
It does indeed look like things are changing since you took over at RESO.  For someone on the outside looking in though it still feel like a members only club and I think RESO could do a lot more to get more open source involvement.
Thanks also for providing your email.  I will contact you by email to follow up on this.  It will be sometime early next week as I want to compose my thoughts a bit better.
Have a great weekend.

**Pull request merged**
